"""initial schema

Revision ID: f7082330f250
Revises: 
Create Date: 2026-06-10 20:42:37.738097

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7082330f250'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('audio_url_fr', sa.String(length=500), nullable=True),
    sa.Column('audio_url_en', sa.String(length=500), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('duration_minutes', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('duration_display', sa.String(length=50), nullable=True),
    sa.Column('departure_longitude', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('departure_latitude', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_source_id'), 'document_chunks', ['source_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_source_type'), 'document_chunks', ['source_type'], unique=False)
    op.create_table('monuments',
    sa.Column('id', sa.Numeric(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('name_fr', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('importance', sa.String(length=100), nullable=True),
    sa.Column('accessibility', sa.String(length=100), nullable=True),
    sa.Column('relief', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('affectation', sa.String(length=100), nullable=True),
    sa.Column('conservation_state', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('visit_duration_minutes', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('opening_time_summer', sa.String(length=50), nullable=True),
    sa.Column('closing_time_summer', sa.String(length=50), nullable=True),
    sa.Column('opening_time_winter', sa.String(length=50), nullable=True),
    sa.Column('closing_time_winter', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('dominant_period', sa.String(length=100), nullable=True),
    sa.Column('secondary_period', sa.String(length=100), nullable=True),
    sa.Column('third_period', sa.String(length=100), nullable=True),
    sa.Column('function', sa.String(length=100), nullable=True),
    sa.Column('price_resident', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_student', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_foreign', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_teacher', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_senior', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_child', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('panoramic_image_url', sa.String(length=500), nullable=True),
    sa.Column('model_object_url', sa.String(length=500), nullable=True),
    sa.Column('video_url_fr', sa.String(length=500), nullable=True),
    sa.Column('video_url_en', sa.String(length=500), nullable=True),
    sa.Column('video_url_ar', sa.String(length=500), nullable=True),
    sa.Column('video_360_url', sa.String(length=500), nullable=True),
    sa.Column('video_3d_url', sa.String(length=500), nullable=True),
    sa.Column('audio_url_fr', sa.String(length=500), nullable=True),
    sa.Column('audio_url_en', sa.String(length=500), nullable=True),
    sa.Column('audio_url_ar', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('circuit_monuments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('monument_id', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monument_id'], ['monuments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circuit_id', 'monument_id', name='uq_circuit_monument')
    )
    op.create_index(op.f('ix_circuit_monuments_circuit_id'), 'circuit_monuments', ['circuit_id'], unique=False)
    op.create_index(op.f('ix_circuit_monuments_monument_id'), 'circuit_monuments', ['monument_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('preference_key', sa.String(length=100), nullable=False),
    sa.Column('preference_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'preference_key', name='uq_session_preference')
    )
    op.create_index(op.f('ix_user_preferences_session_id'), 'user_preferences', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_session_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_circuit_monuments_monument_id'), table_name='circuit_monuments')
    op.drop_index(op.f('ix_circuit_monuments_circuit_id'), table_name='circuit_monuments')
    op.drop_table('circuit_monuments')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('user_sessions')
    op.drop_table('monuments')
    op.drop_index(op.f('ix_document_chunks_source_type'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_source_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('destinations')
    op.drop_table('circuits')
    # ### end Alembic commands ###
