# E:\claude\stage_AI_agentique--master\db.pyi
def test_connexion() -> bool: ...
def charger_tous_clients() -> dict: ...
def charger_tous_circuits() -> list: ...
def charger_client(user_id: str) -> dict | None: ...
def charger_distances_circuit(monuments: list) -> list: ...
def charger_recommandations(user_id: str | None = None) -> list: ...
def sauvegarder_feedback(
    user_id: str, circuit_id: str, note: float, commentaire: str = ""
) -> bool: ...
def sauvegarder_client(profil: dict) -> bool: ...
